import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from "@/components/navbar/Navbar";
import Header from "@/components/header/Header";
import Dashboardprj from "@/components/dashboardprj/Dashboardprj";
import Dashtabs from "@/components/dashtabs/Dashtabs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
        <Navbar />
        <div className="content">
          <Header /> 
          {children}
        </div>
      </body>
    </html>
  );
}
